version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mern-app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://eanushan:TDe8QaxuYHpcxNNu@cluster0.lfqxwj4.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - mern-app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mern-app-network
    depends_on:
      - backend

networks:
  mern-app-network:
    driver: bridge
